-- DROP VIEW current_instance_flow_details;

-- SELECT * FROM performed_exercise;

-- CREATE VIEW current_instance_flow_details AS
-- SELECT
--   flow.user_id AS 'User ID',
--   flow.is_current AS 'Is Current?',
--   flow.template_id AS 'Template ID',
--   flow.template_title AS 'Template Title',
--   flow.instance_id AS 'Instance ID',
--   flow.instance_day_status AS 'Instance Day Status',
--   flow.duration_weeks AS 'Duration in Weeks',
--   flow.week_number AS 'Instance Week --',
--   flow.weekday AS 'Weekday',
--   flow.planned_exercise AS 'Planned Exercise',
--   flow.performed_exercise AS 'Performed Exercise',
--   flow.exercise_order AS 'Exercise Order',
--   flow.performed_status AS 'Performed Status',
--   flow.repeat_until_end AS 'Repeat Until End?',
--   flow.set_order AS 'Set Order',
--   flow.set_weight AS 'Set Weight',
--   flow.set_reps AS 'Set Reps',
--   flow.set_completed AS 'Set Completed?'
-- FROM (
--   -- Union two SELECT statements

--   -- The first SELECT starts from planned_exercise
--   --   - This allows every planned exercise to show, regardless if its been 
--   --   - performed yet. These rows show up with Performed Exercise = NULL.
--   --   - Attaching a performed exercise if one exists.

--   -- The second SELECT starts from performed_exercise
--   --   - This covers exercises added during the workout. Added exercises have
--   --   - no matching planned_exercise row because planned_exercise_id is NULL.

--   -- Together we get the entire picture for the mesocycle instance.
--   SELECT
--     mesocycle_instance.user_id,
--     mesocycle_instance.is_current,
--     mesocycle_template.template_id,
--     mesocycle_template.title AS template_title,
--     mesocycle_instance.instance_id,
--     instance_day.status AS instance_day_status,
--     mesocycle_template.duration_weeks,
--     instance_day.week_number,
--     template_day.day_of_week AS weekday,
--     template_day.day_order,
--     exercise_in_planned.name AS planned_exercise,
--     exercise_in_performed.name AS performed_exercise,
--     COALESCE(performed_exercise.exercise_order, planned_exercise.exercise_order) AS exercise_order,
--     performed_exercise.status AS performed_status,
--     performed_exercise.repeat_until_mesocycle_end AS repeat_until_end,
--     performed_set.set_order,
--     performed_set.weight AS set_weight,
--     performed_set.reps AS set_reps,
--     performed_set.is_completed AS set_completed
--   FROM mesocycle_instance
--   JOIN mesocycle_template
--     ON mesocycle_instance.template_id = mesocycle_template.template_id
--   JOIN instance_day
--     ON instance_day.instance_id = mesocycle_instance.instance_id
--   JOIN template_day
--     ON instance_day.template_day_id = template_day.template_day_id
--   JOIN planned_exercise
--     ON template_day.template_day_id = planned_exercise.template_day_id
--   LEFT JOIN performed_exercise
--     ON performed_exercise.instance_day_id = instance_day.instance_day_id
--     AND performed_exercise.planned_exercise_id = planned_exercise.planned_exercise_id
--   JOIN exercise exercise_in_planned
--     ON exercise_in_planned.exercise_id = planned_exercise.exercise_id
--   LEFT JOIN exercise exercise_in_performed
--     ON exercise_in_performed.exercise_id = performed_exercise.exercise_id
--   LEFT JOIN performed_set 
--     ON performed_set.performed_exercise_id = performed_exercise.performed_exercise_id

--   UNION ALL

--   SELECT
--     mesocycle_instance.user_id,
--     mesocycle_instance.is_current,
--     mesocycle_template.template_id,
--     mesocycle_template.title AS template_title,
--     mesocycle_instance.instance_id,
--     instance_day.status AS instance_day_status,
--     mesocycle_template.duration_weeks,
--     instance_day.week_number,
--     template_day.day_of_week AS weekday,
--     template_day.day_order,
--     NULL AS planned_exercise,
--     exercise_in_performed.name AS performed_exercise,
--     performed_exercise.exercise_order,
--     performed_exercise.status AS performed_status,
--     performed_exercise.repeat_until_mesocycle_end AS repeat_until_end,
--     performed_set.set_order,
--     performed_set.weight AS set_weight,
--     performed_set.reps AS set_reps,
--     performed_set.is_completed AS set_completed
--   FROM mesocycle_instance
--   JOIN mesocycle_template
--     ON mesocycle_instance.template_id = mesocycle_template.template_id
--   JOIN instance_day
--     ON instance_day.instance_id = mesocycle_instance.instance_id
--   JOIN template_day
--     ON instance_day.template_day_id = template_day.template_day_id
--   JOIN performed_exercise
--     ON performed_exercise.instance_day_id = instance_day.instance_day_id
--     AND performed_exercise.planned_exercise_id IS NULL
--   JOIN exercise exercise_in_performed
--     ON exercise_in_performed.exercise_id = performed_exercise.exercise_id
--   LEFT JOIN performed_set 
--     ON performed_set.performed_exercise_id = performed_exercise.performed_exercise_id
-- ) AS flow
-- ORDER BY
--   flow.user_id ASC,
--   flow.is_current DESC,
--   flow.template_id ASC,
--   flow.instance_id ASC,
--   flow.week_number ASC,
--   flow.day_order ASC,
--   flow.exercise_order ASC,
--   flow.set_order ASC;

-- SELECT * FROM current_instance_flow_details;
